project:
  type: book
  output-dir: docs

execute:
  echo: false
  
book:
  title: Introdução ao ![](images/logo.jpg){width=50%}
  author:
    - Lucas S.B. Jordão
    - Marli P. Morim
    - Marcelo F. Simon
    - André Eppinghaus
    - Vicente Calfo
  date: "04/27/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - contexto.qmd
    - diretrizes.qmd
    - tutorial.qmd
    - chamado.qmd
    - conclusao.qmd
    - references.qmd
  favicon: images/logo.jpg
  google-analytics: "G-NY1CF9TG2M"

bibliography: references.bib

format:
  html:
    smooth-scroll: true
    theme:
      light: brite
      dark: cyborg
    number-sections: false
    include-in-header:
      - text: |
          <script src="nav-arrows.js"></script>
          <link href="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css" rel="stylesheet">
    include-after-body: 
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
          <script>
            AOS.init();
          </script>
  pdf:
    documentclass: scrreprt



