# Chamada à ação

Nem Word nem Excel, mas TypeTaxonScript. Estamos à beira de uma nova era nas descrições da taxonomia biológica. Nesta metodologia, são empregados métodos da engenharia de software usando TS para construir uma estrutura de dados robusta, promovendo esforços colaborativos duradouros e não redundantes através da aplicação de uma espécie de engenharia taxonômica dos corpos biológicos. Este programa inovador introduz uma nova abordagem para a documentação precisa e resiliente de táxons e caracteres, transcendendo as limitações dos editores de texto e planilhas tradicionais. O TypeTaxonScript simplifica e otimiza esse processo, permitindo descrições meticulosas e eficientes de organismos diversos, incluindo anotações, impulsionando a ciência da taxonomia e da sistemática a novos níveis de colaboração, precisão e eficácia.

No campo do trabalho colaborativo, mesmo diante de desafios, reside uma oportunidade crítica. Nossa proposta busca incentivar uma adoção mais ampla por parte da comunidade de biólogos, taxonomistas e sistematas. Este esforço implica fornecer uma infraestrutura de acesso aberto que facilite esforços colaborativos, alinhando-se com a criação de classes de objetos. Essa unidade assegura a integridade dos dados, eliminando a necessidade de descrições repetitivas de componentes fundamentais como a classe "folha" em diferentes iniciativas. Ao estruturar atributos das classes, estabelecemos uma abordagem simplificada que facilita o trabalho para futuros colaboradores. Cada descrição exige a instanciação dessas classes como objetos, promovendo uma abordagem semelhante à engenharia taxonômica para criar representações virtuais dos corpos biológicos.

Dentro dessa estrutura colaborativa, os papéis são claramente definidos — alguns se concentram na modelagem do banco de dados, enquanto outros se dedicam ao povoamento de dados. O processo de modelagem envolve a definição das classes de objetos que formam a base do banco de dados. Para alcançar consenso nessa tarefa dinâmica, o envolvimento da comunidade é essencial. Em casos de conflito, a resolução será gerida pelo responsável pelo repositório. Além disso, mesmo hipóteses conflitantes podem coexistir no mesmo banco de dados. Cada hipótese pode ser acomodada como uma classe distinta, permitindo perspectivas diversas e a convivência de diferentes pontos de vista. Essa abordagem inclusiva representa a essência da pesquisa colaborativa, onde as diferenças são valorizadas e contribuem para a riqueza do banco de dados.

Em nosso banco de dados pré-construído [@TTS-Mimosa], adicionamos dados das seguintes publicações: @Jordao2014, @JordaoEtlAl2017, @JordaoEtAl2018, @Vieira2018 e @Jordao2020. Além disso, incorporamos dados iniciais de um projeto de mineração de texto em @Barneby1991 ([https://github.com/lsbjordao/PDF-scraping-Barneby](https://github.com/lsbjordao/PDF-scraping-Barneby)), com o objetivo de compilar uma tabela com todos os caracteres derivados das descrições meticulosas.