# Resumo {.unnumbered}

Artigo publicado: @Jordao_etal_2024

A programação orientada a objetos (POO) representa um paradigma de desenvolvimento de software baseado na representação de entidades do mundo real como objetos, facilitando uma abordagem de modelagem mais eficiente e estruturada. Neste artigo, exploramos a sinergia entre os princípios da POO e a linguagem de programação TypeScript (TS) para criar um banco de dados no formato JSON, projetado para armazenar arrays de características biológicas. Essa fusão de tecnologias promove um script de código controlado e modular, simplificando a integração, manipulação, expansão e análise de dados biológicos, ao mesmo tempo que aprimora a sintaxe para uma melhor legibilidade humana, como o uso da notação de ponto. Defendemos que biólogos adotem a tecnologia Git, semelhante às práticas de programadores e codificadores, para iniciar projetos versionados e colaborativos. O uso do IDE amplamente acessível e renomado, o Visual Studio Code, oferece uma vantagem adicional. Ele não só suporta a execução de um ambiente Node.js, essencial para rodar TS, mas também gerencia eficientemente o versionamento do GitHub. Apresentamos um caso de uso envolvendo a estrutura de dados taxonômica, com foco nas plantas leguminosas angiospermas. Esse método é caracterizado pela sua simplicidade, uma vez que as ferramentas empregadas são totalmente acessíveis e gratuitas, além de ser amplamente adotado por comunidades de programadores profissionais. Além disso, estamos dedicados a facilitar a implementação prática e a compreensão por meio de um tutorial abrangente, um banco de dados pré-construído disponível no GitHub e um novo pacote no npm.